version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=coffee_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1$
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: coffee-machine
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/coffee_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres1$
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
