spring.application.name=machine

spring.datasource.url=jdbc:postgresql://postgres:5432/coffee_db
spring.datasource.username=postgres
spring.datasource.password=postgres1$
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.flyway.enabled=true