spring.application.name=machine

spring.datasource.url=jdbc:postgresql://postgres:5432/coffee_db
spring.datasource.username=postgres
spring.datasource.password=postgres1$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true